WIP

diff --git a/ci/bashly/tpi b/ci/bashly/tpi
--- a/ci/bashly/tpi
+++ b/ci/bashly/tpi
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.7 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -34,14 +34,15 @@ tpi_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
-  printf "  %s   List Shepherd environments owned my our team\n" "list   "
-  printf "  %s   Create a long-lived environment using Shepherd\n" "create "
-  printf "  %s   Install the Telemetry Tile on the specified environment\n" "install"
-  printf "  %s   Upload secrets to Vault\n" "update "
-  printf "  %s   Print telemetry_cli commands\n" "print  "
-  printf "  %s   Get lockfile for foundation, write to local filesystem, and source for cf cli\n" "get    "
-  printf "  %s   Open foundation\n" "open   "
-  printf "  %s   The foundation that is currently targeted\n" "whoami "
+  printf "  %s   List Shepherd environments owned my our team\n" "list    "
+  printf "  %s   Create a long-lived environment using Shepherd\n" "create  "
+  printf "  %s   Install the Telemetry Tile on the specified environment\n" "install "
+  printf "  %s   Upload secrets to Vault\n" "update  "
+  printf "  %s   Print telemetry_cli commands\n" "print   "
+  printf "  %s   Get lockfile for foundation, write to local filesystem, and source for cf cli\n" "get     "
+  printf "  %s   Open foundation\n" "open    "
+  printf "  %s   The foundation that is currently targeted\n" "whoami  "
+  printf "  %s   Ensure that all CI environments exist. Create any needed. Install the Telemetry Tile if needed. Upload secretes to Vault.\n" "maintain"
   echo
 
   # :command.long_usage
@@ -72,13 +73,19 @@ tpi_list_usage() {
   fi
 
   printf "%s\n" "Usage:"
-  printf "  tpi list\n"
+  printf "  tpi list [OPTIONS]\n"
   printf "  tpi list --help | -h\n"
   echo
 
   # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--json"
+    printf "    Return environments as JSON\n"
+    echo
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -385,6 +392,40 @@ tpi_whoami_usage() {
   fi
 }
 
+# :command.usage
+tpi_maintain_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "tpi maintain - Ensure that all CI environments exist. Create any needed. Install the Telemetry Tile if needed. Upload secretes to Vault.\n"
+    echo
+
+  else
+    printf "tpi maintain - Ensure that all CI environments exist. Create any needed. Install the Telemetry Tile if needed. Upload secretes to Vault.\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  tpi maintain\n"
+  printf "  tpi maintain --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  tpi maintain\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -549,7 +590,11 @@ set_shepherd_binary_path() {
 # :command.function
 tpi_list_command() {
   # src/list_command.sh
-  $SHEPHERD_BINARY_PATH list lease --wide --namespace=tpi-telemetry
+  if [[ ${args[--json]} == "1" ]]; then
+  	$SHEPHERD_BINARY_PATH list lease --json --wide --namespace=tpi-telemetry
+  else
+  	$SHEPHERD_BINARY_PATH list lease --wide --namespace=tpi-telemetry
+  fi
 
 }
 
@@ -590,6 +635,9 @@ tpi_create_command() {
   	if [[ "$TELEMETRY_TILE_INSTALL_REQUIRED" == "true" ]]; then
   		echo -e "Install Telemetry Tile before updating Vault variables\n"
   	fi
+
+  	# Remove old metadata file
+  	rm -rf "${PWD}/shepherd_envs/$ENV_DESCRIPTION-metadata.json"
   else
   	echo -e "$ENV_DESCRIPTION already exists\n"
   fi
@@ -896,6 +944,8 @@ tpi_get_command() {
   eval $(smith om -l "$LOCKFILE_PATH")
   eval $(smith bosh -l "$LOCKFILE_PATH")
 
+  echo -e "\n*** BOSH_ENVIRONMENT ***\n$BOSH_ENVIRONMENT"
+
   echo -e "\nGetting env variables...\n"
 
   # Function to get ops_manager password
@@ -1013,6 +1063,7 @@ tpi_open_command() {
 # :command.function
 tpi_whoami_command() {
   # src/whoami_command.sh
+  # FIXME: only works for environments with TAS, won't detect if environment has been reaped
   export SYS_DOMAIN=$(cf api | grep 'API endpoint' | awk '{print $3}' | cut -d'/' -f3 | sed 's/^api\.//') || ""
 
   if [[ -z $SYS_DOMAIN ]]; then
@@ -1051,6 +1102,116 @@ tpi_whoami_command() {
   fi
 
   echo -e "Targeted foundation does not match a Shepherd Env"
+
+}
+
+# :command.function
+tpi_maintain_command() {
+  # src/maintain_command.sh
+  export ENVS_JSON=$(tpi_list_command --json)
+  export CI_ENVS=(production-jammy acceptance-jammy staging-jammy production-xenial acceptance-xenial staging-xenial)
+  mkdir -p "${PWD}/shepherd_envs"
+
+  # Function that takes in a string and returns a boolean.
+  # Checks to see if if there is a JSON object within ENVS_JSON
+  # where the value of the "description" key is set to the value of
+  # the string we're processing from CI_ENVS
+  env_exists() {
+  	if echo "$ENVS_JSON" | jq -r --arg env "$1" '.[] | select(.description == "$env")' &> /dev/null; then
+  		return 0
+  	else
+  		return 1
+  	fi
+  }
+
+  # Function that takes in a string and returns a boolean.
+  # Checks to see if environment is ready by checking for
+  # existance of lockfile.
+  env_ready() {
+  	if [[ $LOCKFILE_DATA == null ]]; then
+  		return 1
+  	else
+  		return 0
+  	fi
+  }
+
+  # Function to get Telemetry Tile guid
+  telemetry_installed() {
+  	export TELEMETRY_TILE_GUID=$(smith om --lockfile="$LOCKFILE_PATH" -- curl -s --path /api/v0/deployed/products | jq -r '.[] | select(.type == "pivotal-telemetry-om").guid') || ""
+  	if [[ -z "$TELEMETRY_TILE_GUID" ]]; then
+  		return 1
+  	else
+  		return 0
+  	fi
+  }
+
+  check_all_envs_exist() {
+  	echo -e "Checking that all enivronments exist..."
+  	for my_env in "$CI_ENVS[@]"; do
+  		extract_env_details "$my_env"
+  		export LOCKFILE_PATH=${PWD}/shepherd_envs/$my_env-metadata.json
+  	  	export ENV_TYPE=$(echo "$my_env" | cut -d '-' -f 1)
+
+  		if ! env_exists "$my_env"; then
+  			printf "No match for %s: creating new env...\n" "$my_env"
+  			tpi_create_command "$my_env"
+  			exit 0
+  	  	fi
+  	 done
+
+  	 echo "*** All environments exist. ***"
+  }
+
+  check_all_envs_ready() {
+  	echo -e "Checking that all enivronments are ready..."
+  	for my_env in "$CI_ENVS[@]"; do
+  		extract_env_details "$my_env"
+  		export LOCKFILE_PATH=${PWD}/shepherd_envs/$my_env-metadata.json
+  	  	export ENV_TYPE=$(echo "$my_env" | cut -d '-' -f 1)
+  		if ! env_ready; then
+  			printf "%s not ready. Please wait.\n" "$my_env"
+  			exit 0
+  		fi
+  	done
+
+  	echo "*** All environments ready. ***"
+  }
+
+  check_telemetry_tile_installed() {
+  	echo -e "Checking that Telemetry Tile is installed..."
+  	for my_env in "$CI_ENVS[@]"; do
+  		extract_env_details "$my_env"
+  		export LOCKFILE_PATH=${PWD}/shepherd_envs/$my_env-metadata.json
+  	  	export ENV_TYPE=$(echo "$my_env" | cut -d '-' -f 1)
+  		if [[ $ENV_TYPE != "staging" ]]; then
+  			if [[ ! telemetry_installed ]]; then
+  				printf "Installing the Telemetry Tile"
+  				tpi_install_command "$my_env"
+  				exit 0
+  			fi
+  		fi
+  	done
+
+  	echo "*** Telemetry Tile installed. ***"
+  }
+
+  upload_secrets_to_vault() {
+  	echo -e "Uploading secrets to Vault..."
+  	for my_env in "$CI_ENVS[@]"; do
+  		extract_env_details "$my_env"
+  		export LOCKFILE_PATH=${PWD}/shepherd_envs/$my_env-metadata.json
+  	  	export ENV_TYPE=$(echo "$my_env" | cut -d '-' -f 1)
+
+  	  	tpi_update_command "$my_env"
+  	 done
+
+  	 echo "*** Secrets uploaded to Vault. ***"
+  }
+
+  check_all_envs_exist
+  check_all_envs_ready
+  check_telemetry_tile_installed
+  upload_secrets_to_vault
 
 }
 
@@ -1203,6 +1364,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    maintain)
+      action="maintain"
+      shift
+      tpi_maintain_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       tpi_usage >&2
@@ -1264,6 +1432,13 @@ tpi_list_parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+      # :flag.case
+      --json)
+
+        # :flag.case_no_arg
+        args['--json']=1
+        shift
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -1318,7 +1493,6 @@ tpi_create_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['foundation']+x} ]]; then
-
           args['foundation']=$1
           shift
         else
@@ -1380,7 +1554,6 @@ tpi_install_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['foundation']+x} ]]; then
-
           args['foundation']=$1
           shift
         else
@@ -1442,7 +1615,6 @@ tpi_update_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['foundation']+x} ]]; then
-
           args['foundation']=$1
           shift
         else
@@ -1504,7 +1676,6 @@ tpi_print_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['foundation']+x} ]]; then
-
           args['foundation']=$1
           shift
         else
@@ -1566,7 +1737,6 @@ tpi_get_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['foundation']+x} ]]; then
-
           args['foundation']=$1
           shift
         else
@@ -1628,7 +1798,6 @@ tpi_open_parse_requirements() {
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
         if [[ -z ${args['foundation']+x} ]]; then
-
           args['foundation']=$1
           shift
         else
@@ -1699,6 +1868,50 @@ tpi_whoami_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+tpi_maintain_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        tpi_maintain_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="maintain"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.user_hooks
 before_hook() {
   # src/before.sh
@@ -1737,6 +1950,7 @@ run() {
     "get") tpi_get_command ;;
     "open") tpi_open_command ;;
     "whoami") tpi_whoami_command ;;
+    "maintain") tpi_maintain_command ;;
   esac
 }
 
