tpi binary updates

diff --git a/ci/bashly/tpi b/ci/bashly/tpi
--- a/ci/bashly/tpi
+++ b/ci/bashly/tpi
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.7 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -45,6 +45,7 @@ tpi_usage() {
   printf "  %s   Ensure that all CI environments exist. Create any needed. Install the Telemetry Tile if needed. Upload secretes to Vault.\n" "maintain"
   printf "  %s   Open Ops Manager for a provided Shepherd lease\n" "lease   "
   printf "  %s   Given an Ops Manager version, get the corresponding Telemetry Tile version\n" "version "
+  printf "  %s   Create TKGi test env\n" "tkgi    "
   echo
 
   # :command.long_usage
@@ -516,13 +517,51 @@ tpi_version_usage() {
   fi
 }
 
+# :command.usage
+tpi_tkgi_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "tpi tkgi - Create TKGi test env\n"
+    echo
+
+  else
+    printf "tpi tkgi - Create TKGi test env\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  tpi tkgi\n"
+  printf "  tpi tkgi --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  tpi tkgi\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-  local arg flags
+  local arg flags passthru
+  passthru=false
 
   while [[ $# -gt 0 ]]; do
     arg="$1"
-    if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+    if [[ $passthru == true ]]; then
+      input+=("$arg")
+    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
       input+=("${BASH_REMATCH[1]}")
       input+=("${BASH_REMATCH[2]}")
     elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -533,6 +572,9 @@ normalize_input() {
       for ((i = 0; i < ${#flags}; i++)); do
         input+=("-${flags:i:1}")
       done
+    elif [[ "$arg" == "--" ]]; then
+      passthru=true
+      input+=("$arg")
     else
       input+=("$arg")
     fi
@@ -540,6 +582,7 @@ normalize_input() {
     shift
   done
 }
+
 # :command.inspect_args
 inspect_args() {
   if ((${#args[@]})); then
@@ -1557,6 +1600,12 @@ tpi_maintain_command() {
   check_all_envs_exist
   check_telemetry_tile_installed
 
+  # Let the Telemetry Tile install
+  sleep 5
+  echo -e "Waiting for background jobs to finish..."
+  wait $(jobs -p)
+  echo -e "Background jobs complete."
+
   echo -e "ALL_ENVS_READY: $ALL_ENVS_READY"
   if [ "$ALL_ENVS_READY" = true ]; then
   	echo -e "*** ALL ENVS READY ***"
@@ -1618,6 +1667,13 @@ tpi_version_command() {
   echo -e "**************************\n"
   git switch - &>/dev/null
   cd ~/workspace/tile/aqueduct-courier/ci/bashly
+
+}
+
+# :command.function
+tpi_tkgi_command() {
+  # src/tkgi_command.sh
+  $SHEPHERD_BINARY_PATH lock create --file "$PWD/config/tkgi-recipe.json" --lifetime 7d --description "tkgi-test-env-1-tpi"
 
 }
 
@@ -1791,6 +1847,13 @@ parse_requirements() {
       shift $#
       ;;
 
+    tkgi)
+      action="tkgi"
+      shift
+      tpi_tkgi_parse_requirements "$@"
+      shift $#
+      ;;
+
     # :command.command_fallback
     "")
       tpi_usage >&2
@@ -1912,6 +1975,7 @@ tpi_create_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['foundation']+x} ]]; then
           args['foundation']=$1
           shift
@@ -1973,6 +2037,7 @@ tpi_install_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['foundation']+x} ]]; then
           args['foundation']=$1
           shift
@@ -2034,6 +2099,7 @@ tpi_update_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['foundation']+x} ]]; then
           args['foundation']=$1
           shift
@@ -2102,6 +2168,7 @@ tpi_print_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['foundation']+x} ]]; then
           args['foundation']=$1
           shift
@@ -2163,6 +2230,7 @@ tpi_get_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['foundation']+x} ]]; then
           args['foundation']=$1
           shift
@@ -2218,6 +2286,7 @@ tpi_open_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['foundation']+x} ]]; then
           args['foundation']=$1
           shift
@@ -2361,6 +2430,7 @@ tpi_lease_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['id']+x} ]]; then
           args['id']=$1
           shift
@@ -2416,6 +2486,7 @@ tpi_version_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
+        # :argument.case
         if [[ -z ${args['tag']+x} ]]; then
           args['tag']=$1
           shift
@@ -2434,6 +2505,50 @@ tpi_version_parse_requirements() {
     printf "missing required argument: TAG\nusage: tpi version TAG\n" >&2
     exit 1
   fi
+
+}
+
+# :command.parse_requirements
+tpi_tkgi_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        tpi_tkgi_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="tkgi"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
 
 }
 
@@ -2479,6 +2594,7 @@ run() {
     "maintain") tpi_maintain_command ;;
     "lease") tpi_lease_command ;;
     "version") tpi_version_command ;;
+    "tkgi") tpi_tkgi_command ;;
   esac
 }
 
