Updates to tpi cli

diff --git a/ci/bashly/tpi b/ci/bashly/tpi
--- a/ci/bashly/tpi
+++ b/ci/bashly/tpi
@@ -41,6 +41,7 @@ tpi_usage() {
   printf "  %s   Print telemetry_cli commands\n" "print  "
   printf "  %s   Get lockfile for foundation, write to local filesystem, and source for cf cli\n" "get    "
   printf "  %s   Open foundation\n" "open   "
+  printf "  %s   The foundation that is currently targeted\n" "whoami "
   echo
 
   # :command.long_usage
@@ -350,6 +351,40 @@ tpi_open_usage() {
   fi
 }
 
+# :command.usage
+tpi_whoami_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "tpi whoami - The foundation that is currently targeted\n"
+    echo
+
+  else
+    printf "tpi whoami - The foundation that is currently targeted\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  tpi whoami\n"
+  printf "  tpi whoami --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_examples
+    printf "%s\n" "Examples:"
+    printf "  tpi whoami\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -415,6 +450,24 @@ inspect_args() {
 }
 
 # :command.user_lib
+# src/lib/ensure_pivnet_login.sh
+ensure_pivnet_login() {
+  # Get Pivnet token
+  export PIVNET_REFRESH_TOKEN=$(vault kv get -format=json /runway_concourse/tanzu-portfolio-insights/pivnet | jq -r '.data' | jq -r '.["refresh-token"]')
+
+  # export PIVNET_ACCESS_TOKEN=$(curl -X POST https://network.tanzu.vmware.com/api/v2/authentication/access_tokens -d '{"refresh_token":$PIVNET_REFRESH_TOKEN}' | jq -r .access_token)
+  # curl -X GET https://network.tanzu.vmware.com/api/v2/authentication -H "Authorization: Bearer $PIVNET_ACCESS_TOKEN"
+
+  if ! pivnet login --api-token=$PIVNET_REFRESH_TOKEN &>/dev/null; then
+    echo "Failed to login to pivnet" >&2
+    echo "Attempting again..."
+    if ! pivnet login --api-token=$PIVNET_REFRESH_TOKEN &>/dev/null; then
+      echo "Failed to login to pivnet a 2nd time" >&2
+      exit 0
+    fi
+  fi
+}
+
 # src/lib/ensure_shepherd_login.sh
 ensure_shepherd_login() {
   #export SHEPHERD_TOKEN=$(vault kv get -format=json /runway_concourse/tanzu-portfolio-insights/shepherd/tpi-telemetry | jq -r .data.secret)
@@ -549,10 +602,115 @@ tpi_create_command() {
 # :command.function
 tpi_install_command() {
   # src/install_command.sh
-  extract_env_details ${args[foundation]}
+  tpi_get_command ${args[foundation]}
 
-  echo -e "Check that this foundation doesn't already have the tile installed"
-  echo -e "Do the installation of the Tile"
+  LOCKFILE_PATH="${PWD}/shepherd_envs/${args[foundation]}-metadata.json"
+
+  # Check that this foundation doesn't already have the Telemetry Tile installed
+  export TELEMETRY_TILE_GUID=$(smith om --lockfile="${PWD}/shepherd_envs/${args[foundation]}-metadata.json" -- curl -s --path /api/v0/deployed/products | jq -r '.[] | select(.type == "pivotal-telemetry-om").guid') || ""
+  if [[ -n "$TELEMETRY_TILE_GUID" ]]; then
+  	echo -e "\nThe Telemetry Tile is already installed\n"
+  	exit 0
+  fi
+
+  smith cf-login --lockfile="$LOCKFILE_PATH"
+  eval $(smith om -l "$LOCKFILE_PATH")
+  eval $(smith bosh -l "$LOCKFILE_PATH")
+
+  # Enable the Usage Service Errand
+  export TAS_TILE_GUID=$(om curl --silent --path /api/v0/deployed/products | jq -r '.[] | select(.type == "cf").guid')
+  om curl --silent --path "/api/v0/staged/products/$TAS_TILE_GUID/errands" -x PUT -d '{"errands":[{"name":"push-usage-service","post_deploy":true}]}'
+
+  # errand_exists=$(bosh errands --json | jq -r '.["Tables"]' | jq -r '.[0]' | jq -r '.["Rows"]' | jq 'any(.[]; .name == "push-usage-service")')
+  # CF_DEPLOYMENT="$(bosh deployments --json | jq -r '.Tables[] | select(.Content="deployments") | .Rows[] | select(.name | test("^cf-")) | .name')"
+  # bosh run-errand -d "$CF_DEPLOYMENT" push-usage-service
+
+  # Get details of latest Telemetry Tile
+  # PRODUCT_NAME="pivotal-telemetry-om"
+  # TILE_INFO_JSON=$(pivnet releases --format=json -p "$PRODUCT_NAME" -l 1)
+  # TILE_VERSION=$(echo $TILE_INFO_JSON | jq -r '.[0].version')
+
+  TILE_FULL_VERSION=$(om products --format=json | jq '.[] | select(.name == "pivotal-telemetry-om")' | jq -r .available | jq -r '.[0]')
+
+  # Download latest Telemetry Tile
+  # rm -rf /tmp/tile
+  # mkdir /tmp/tile
+  # pivnet download-product-files --accept-eula --download-dir=/tmp/tile -p "$PRODUCT_NAME" -r "$TILE_VERSION" -g "*.pivotal"
+
+  network="$(smith read --lockfile=$LOCKFILE_PATH | jq -r .ert_subnet)"
+  az="us-central1-f"
+
+  function retry {
+    local retries=$1
+    local count=0
+    shift
+
+    until "$@"; do
+      exit=$?
+      count=$(($count + 1))
+      if [ $count -lt $retries ]; then
+        echo "Attempt $count/$retries ended with exit $exit"
+        # Need a short pause between smith CLI executions or it fails unexpectedly.
+        sleep 30
+      else
+        echo "Attempted $count/$retries times and failed."
+        return $exit
+      fi
+    done
+    return 0
+  }
+
+  LOADER_API_KEY=$(vault kv get -format=json /runway_concourse/tanzu-portfolio-insights/aqueduct-loader | jq -r '.data' | jq -r '.["production-loader-api-keys"]' | jq -r '.["Telemetry and Insights"]' | jq -r '.[0]')
+  echo -e "Loader API Key:\t$LOADER_API_KEY"
+
+  # echo "Uploading tile..."
+  # retry 5 smith om --lockfile=$LOCKFILE_PATH -- upload-product --product "/tmp/tile/pivotal-telemetry-om-$TILE_VERSION.pivotal"
+
+  echo "Staging tile..."
+  retry 5 om stage-product \
+     --product-name "pivotal-telemetry-om" \
+     --product-version "$TILE_FULL_VERSION"
+
+  FOUNDATION_NICKNAME=$(cat $LOCKFILE_PATH | jq .name)
+  TILE_ENV_TYPE=$ENV_TYPE
+  if [[ $ENV_TYPE == "acceptance" ]]; then
+  	TILE_ENV_TYPE="qa"
+  	FOUNDATION_NICKNAME="best-acceptance-env"
+  fi
+
+  echo "Configuring tile..."
+  retry 5 om configure-product \
+     --config "$HOME/workspace/tile/p-telemetry/ci/tasks/product-config.yml" \
+     --var audit-mode="false" \
+     --var env-type="$TILE_ENV_TYPE" \
+     --var foundation-nickname="$FOUNDATION_NICKNAME" \
+     --var loader-endpoint="https://telemetry.pivotal.io" \
+     --var telemetry-api-key="$LOADER_API_KEY" \
+     --var flush-interval=10 \
+     --var collector-cron-schedule="0 8 * * *" \
+     --var network="$network" \
+     --var az="$az" \
+     --var ops-manager-timeout=30 \
+     --var ops-manager-request-timeout=15
+
+  # echo "Uploading stemcell..."
+  # retry 5 smith om -- upload-stemcell --stemcell stemcell/*.tgz
+
+  # echo "Assigning stemcell to tile..."
+  # retry 5 smith om -- assign-stemcell \
+  #    --product pivotal-telemetry-om
+
+  smith open --lockfile="$LOCKFILE_PATH"
+
+  echo "Applying changes..."
+  rm -rf /tmp/bashly/logs
+  mkdir -p /tmp/bashly/logs
+  LOG_FILE=/tmp/bashly/logs/${args[foundation]}.log
+  touch $LOG_FILE
+  nohup om apply-changes --reattach > $LOG_FILE 2>&1 &
+
+  echo -e "Run the following command to watch the install:\n"
+  echo -e "tail -f ${LOG_FILE}"
 
 }
 
@@ -740,10 +898,11 @@ tpi_get_command() {
   	echo "$LOCKFILE_DATA" >"$LOCKFILE_PATH"
   fi
 
-  # Source envs
+  # Source envs for smith, cf, bosh CLIs
   echo -e "Targeting ${args[foundation]}..."
-  eval "$(smith om --lockfile="$LOCKFILE_PATH")"
   smith cf-login --lockfile="$LOCKFILE_PATH"
+  eval $(smith om -l "$LOCKFILE_PATH")
+  eval $(smith bosh -l "$LOCKFILE_PATH")
 
   echo -e "\nGetting env variables...\n"
 
@@ -771,28 +930,6 @@ tpi_get_command() {
   	echo -e "P_BOSH_ID:\t\t\t\t$P_BOSH_ID"
   }
 
-  # Function to get Telemetry Tile guid
-  fetch_telemetry_tile_guid() {
-  	if [[ $ENV_TYPE != "staging" ]]; then
-  		export TELEMETRY_TILE_GUID=$(smith om --lockfile="$LOCKFILE_PATH" -- curl -s --path /api/v0/deployed/products | jq -r '.[] | select(.type == "pivotal-telemetry-om").guid') || ""
-
-  		if [[ -z "$TELEMETRY_TILE_GUID" ]]; then
-  			echo -e "\n*** YOU MUST INSTALL THE TELEMETRY TILE ***\n"
-  			exit 0
-  		fi
-
-  		echo -e "TELEMETRY_TILE_GUID:\t\t\t$TELEMETRY_TILE_GUID"
-  	fi
-  }
-
-  # Function to get uaa_client_secret
-  fetch_uaa_client_secret() {
-  	if [[ $ENV_TYPE != "staging" ]]; then
-  		export UAA_CLIENT_SECRET=$(smith om --lockfile="$LOCKFILE_PATH" -- curl -s --path /api/v0/deployed/products/"${TELEMETRY_TILE_GUID}"/manifest | jq -r '.instance_groups[] | select(.name == "telemetry-centralizer").jobs[] | select(.name == "telemetry-collector").properties.opsmanager.auth.uaa_client_secret')
-  		echo -e "UAA_CLIENT_SECRET:\t\t\t$UAA_CLIENT_SECRET"
-  	fi
-  }
-
   # Function to get cf_guid
   fetch_cf_guid() {
   	export CF_GUID=$(smith om --lockfile="$LOCKFILE_PATH" -- curl -s --path /api/v0/deployed/products | jq -r '.[] | select(.type == "cf").guid')
@@ -810,6 +947,36 @@ tpi_get_command() {
   	echo -e "GCP_PROJECT_ID:\t\t\t\t$GCP_PROJECT_ID"
   }
 
+  # Function to get name
+  fetch_name() {
+  	export NAME=$(smith read --lockfile="$LOCKFILE_PATH" | jq -r .name)
+  	echo -e "NAME:\t\t\t\t\t$NAME"
+  }
+
+  export FOUNDATION=${args[foundation]}
+
+
+  # Function to get Telemetry Tile guid
+  fetch_telemetry_tile_guid() {
+  	if [[ $ENV_TYPE != "staging" ]]; then
+  		export TELEMETRY_TILE_GUID=$(smith om --lockfile="$LOCKFILE_PATH" -- curl -s --path /api/v0/deployed/products | jq -r '.[] | select(.type == "pivotal-telemetry-om").guid') || ""
+  		echo -e "TELEMETRY_TILE_GUID:\t\t\t$TELEMETRY_TILE_GUID"
+  	fi
+  }
+
+  # Function to get uaa_client_secret
+  fetch_uaa_client_secret() {
+  	if [[ $ENV_TYPE != "staging" ]]; then
+
+  		if [[ -z "$TELEMETRY_TILE_GUID" ]]; then
+  			echo -e "UAA_CLIENT_SECRET:"
+  		else
+  			export UAA_CLIENT_SECRET=$(smith om --lockfile="$LOCKFILE_PATH" -- curl -s --path /api/v0/deployed/products/"${TELEMETRY_TILE_GUID}"/manifest | jq -r '.instance_groups[] | select(.name == "telemetry-centralizer").jobs[] | select(.name == "telemetry-collector").properties.opsmanager.auth.uaa_client_secret')
+  			echo -e "UAA_CLIENT_SECRET:\t\t\t$UAA_CLIENT_SECRET"
+  		fi
+  	fi
+  }
+
   # Function to make an API call using the cf_guid and print the telemetry_usage_service_password
   fetch_telemetry_usage_service_password() {
   	export TELEMETRY_USAGE_SERVICE_PASSWORD=""
@@ -819,30 +986,28 @@ tpi_get_command() {
   			TELEMETRY_USAGE_SERVICE_PASSWORD=$(smith om --lockfile="$LOCKFILE_PATH" -- curl -s --path /api/v0/deployed/products/"${CF_GUID}"/credentials/.uaa.usage_service_client_credentials | jq -r .credential.value.password)
   			echo -e "TELEMETRY_USAGE_SERVICE_PASSWORD:\t$TELEMETRY_USAGE_SERVICE_PASSWORD"
   		else
-  			echo -e "\n*** YOU MUST INSTALL THE TELEMETRY TILE ***\n"
-  			exit 0
+  			echo -e "TELEMETRY_USAGE_SERVICE_PASSWORD:"
   		fi
   	else
   		echo -e "TELEMETRY_USAGE_SERVICE_PASSWORD:"
   	fi
   }
 
-  # Function to get name
-  fetch_name() {
-  	export NAME=$(smith read --lockfile="$LOCKFILE_PATH" | jq -r .name)
-  	echo -e "NAME:\t\t\t\t\t$NAME"
-  }
-
   fetch_ops_manager_pw
   fetch_ops_manager_username
   fetch_ops_manager_url
   fetch_p_bosh_id
-  fetch_telemetry_tile_guid
-  fetch_uaa_client_secret
-  fetch_cf_guid
-  fetch_telemetry_usage_service_password
   fetch_gcp_project_id
   fetch_name
+  fetch_cf_guid
+
+  fetch_telemetry_tile_guid
+  fetch_uaa_client_secret
+  fetch_telemetry_usage_service_password
+
+  if [[ -z "$TELEMETRY_TILE_GUID" ]]; then
+  	echo -e "\n*** YOU MUST INSTALL THE TELEMETRY TILE ***\n"
+  fi
 
 }
 
@@ -850,6 +1015,50 @@ tpi_get_command() {
 tpi_open_command() {
   # src/open_command.sh
   smith open --lockfile="${PWD}/shepherd_envs/${args[foundation]}-metadata.json"
+
+}
+
+# :command.function
+tpi_whoami_command() {
+  # src/whoami_command.sh
+  export SYS_DOMAIN=$(cf api | grep 'API endpoint' | awk '{print $3}' | cut -d'/' -f3 | sed 's/^api\.//') || ""
+
+  if [[ -z $SYS_DOMAIN ]]; then
+  	echo -e "No foundations targeted"
+  	exit 0
+  fi
+
+  if [ $(cat shepherd_envs/acceptance-jammy-metadata.json | jq -r .sys_domain) = $SYS_DOMAIN ]; then
+  	echo -e "acceptance-jammy"
+  	exit 0
+  fi
+
+  if [ $(cat shepherd_envs/acceptance-xenial-metadata.json | jq -r .sys_domain) = $SYS_DOMAIN ]; then
+  	echo -e "acceptance-xenail"
+  	exit 0
+  fi
+
+  if [ $(cat shepherd_envs/production-jammy-metadata.json | jq -r .sys_domain) = $SYS_DOMAIN ]; then
+  	echo -e "production-jammy"
+  	exit 0
+  fi
+
+  if [ $(cat shepherd_envs/production-xenial-metadata.json | jq -r .sys_domain) = $SYS_DOMAIN ]; then
+  	echo -e "production-xenial"
+  	exit 0
+  fi
+
+  if [ $(cat shepherd_envs/staging-jammy-metadata.json | jq -r .sys_domain) = $SYS_DOMAIN ]; then
+  	echo -e "staging-jammy"
+  	exit 0
+  fi
+
+  if [ $(cat shepherd_envs/staging-xenial-metadata.json | jq -r .sys_domain) = $SYS_DOMAIN ]; then
+  	echo -e "staging-xenial"
+  	exit 0
+  fi
+
+  echo -e "Targeted foundation does not match a Shepherd Env"
 
 }
 
@@ -877,17 +1086,24 @@ parse_requirements() {
   done
 
   # :command.dependencies_filter
-  if command -v shepherd >/dev/null 2>&1; then
-    deps['shepherd']="$(command -v shepherd | head -n1)"
+  if command -v bosh >/dev/null 2>&1; then
+    deps['bosh']="$(command -v bosh | head -n1)"
   else
-    printf "missing dependency: shepherd\n" >&2
+    printf "missing dependency: bosh\n" >&2
     exit 1
   fi
 
-  if command -v vault >/dev/null 2>&1; then
-    deps['vault']="$(command -v vault | head -n1)"
+  if command -v cf >/dev/null 2>&1; then
+    deps['cf']="$(command -v cf | head -n1)"
   else
-    printf "missing dependency: vault\n" >&2
+    printf "missing dependency: cf\n" >&2
+    exit 1
+  fi
+
+  if command -v curl >/dev/null 2>&1; then
+    deps['curl']="$(command -v curl | head -n1)"
+  else
+    printf "missing dependency: curl\n" >&2
     exit 1
   fi
 
@@ -898,13 +1114,6 @@ parse_requirements() {
     exit 1
   fi
 
-  if command -v smith >/dev/null 2>&1; then
-    deps['smith']="$(command -v smith | head -n1)"
-  else
-    printf "missing dependency: smith\n" >&2
-    exit 1
-  fi
-
   if command -v om >/dev/null 2>&1; then
     deps['om']="$(command -v om | head -n1)"
   else
@@ -912,17 +1121,31 @@ parse_requirements() {
     exit 1
   fi
 
-  if command -v bosh >/dev/null 2>&1; then
-    deps['bosh']="$(command -v bosh | head -n1)"
+  if command -v pivnet >/dev/null 2>&1; then
+    deps['pivnet']="$(command -v pivnet | head -n1)"
   else
-    printf "missing dependency: bosh\n" >&2
+    printf "missing dependency: pivnet\n" >&2
     exit 1
   fi
 
-  if command -v curl >/dev/null 2>&1; then
-    deps['curl']="$(command -v curl | head -n1)"
+  if command -v shepherd >/dev/null 2>&1; then
+    deps['shepherd']="$(command -v shepherd | head -n1)"
   else
-    printf "missing dependency: curl\n" >&2
+    printf "missing dependency: shepherd\n" >&2
+    exit 1
+  fi
+
+  if command -v smith >/dev/null 2>&1; then
+    deps['smith']="$(command -v smith | head -n1)"
+  else
+    printf "missing dependency: smith\n" >&2
+    exit 1
+  fi
+
+  if command -v vault >/dev/null 2>&1; then
+    deps['vault']="$(command -v vault | head -n1)"
+  else
+    printf "missing dependency: vault\n" >&2
     exit 1
   fi
 
@@ -978,6 +1201,13 @@ parse_requirements() {
       action="open"
       shift
       tpi_open_parse_requirements "$@"
+      shift $#
+      ;;
+
+    whoami)
+      action="whoami"
+      shift
+      tpi_whoami_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1433,12 +1663,57 @@ tpi_open_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+tpi_whoami_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        tpi_whoami_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="whoami"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.user_hooks
 before_hook() {
   # src/before.sh
   set_shepherd_binary_path
   ensure_vault_login
   ensure_shepherd_login
+  ensure_pivnet_login
 
 }
 
@@ -1469,6 +1744,7 @@ run() {
     "print") tpi_print_command ;;
     "get") tpi_get_command ;;
     "open") tpi_open_command ;;
+    "whoami") tpi_whoami_command ;;
   esac
 }
 
